### ISSUE TITLE
google is not defined

### ISSUE THREAD

**Issue by jkowensky** [BraftonSupport/braftonium-new#102]
Map not showing on backend and I get this error in the Console for the front end.

https://github.com/BraftonSupport/braftonium-new/blob/463f9ef5e7082e727deedc657633f3160dce3209/blocks/google-map/google-map.html.php#L97

Uncaught ReferenceError: google is not defined
    at initMap ((index):197:31)
    at HTMLDivElement.<anonymous> ((index):294:27)
    at Function.each (jquery.min.js?ver=3.6.1:2:3003)
    at s.fn.init.each (jquery.min.js?ver=3.6.1:2:1481)
    at HTMLDocument.<anonymous> ((index):293:27)
    at e (jquery.min.js?ver=3.6.1:2:30038)
    at t (jquery.min.js?ver=3.6.1:2:30340)

**Comment by jkowensky** [comment]
Now I get this ... let's setup a meeting when time works.
![image](https://user-images.githubusercontent.com/87807140/203552840-d50485c4-5902-413a-be43-024f3069b240.png)

**Comment by allanjames** [comment]
@jkowensky 
Very interesting. Let me take another look on my side and then I will see about scheduling some time. I'd like to see if I have those notices in my error logs. Cheers

**Comment by allanjames** [comment]
@jkowensky 
I'm getting the same bloody notice when I add a map to the page in my logs. It does not however effect the rendering of the map. I will address this however.

**Comment by allanjames** [comment]
@jkowensky 
I just opened one new pull request. I've wrapped the entire contents of the Template file in a conditional to check for the admin screen.  This eliminates those pesky warning notices for undefined indexes.

**Comment by jkowensky** [comment]
Keeping this open
